on: [push, pull_request]
name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-18.04, macos-10.15]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Setup github PATH
        run: |
          echo `pwd`/bin >> $GITHUB_PATH
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          export XVM_BUILD_MAIN=1
          diff -u <(echo -n) <(gofmt -d $(find . -type f -name '*.go'))
          make && make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
